name: 🏗 Build on CI

on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: [ self-hosted, macOS, ARM64 ]
    steps:
      - uses: actions/checkout@v3

      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install Taskfile
        run: brew install go-task

      - name: Setup Rust Toolchain
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: nightly
          targets: 'aarch64-apple-darwin x86_64-apple-darwin'

      - name: Build
        run: task build-universal

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: swift-precompiler
          path: target/swift-precompiler

      - uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "deploy"
          description: "Build swift-precompiler"
          url: "https://github.com/ciderapp/swift-precompiler/actions"
          username: GitHub Actions
          avatar_url: "https://avatars.githubusercontent.com/u/87914859?s=200&v=4"
